version: '3.7'
services:
  game:
    build: .
    ports:
      - "5000"
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - game
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"